<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CiudadesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ciudades = [
            ['nombre' => 'Abejorral', 'departamento_id' => 2],
            ['nombre' => 'Abriaquí', 'departamento_id' => 2],
            ['nombre' => 'Alejandría', 'departamento_id' => 2],
            ['nombre' => 'Amalfi', 'departamento_id' => 2],
            ['nombre' => 'Andes', 'departamento_id' => 2],
            ['nombre' => 'Angelópolis', 'departamento_id' => 2],
            ['nombre' => 'Angostura', 'departamento_id' => 2],
            ['nombre' => 'Anorí', 'departamento_id' => 2],
            ['nombre' => 'Santa Fé de Antioquia', 'departamento_id' => 2],
            ['nombre' => 'Anzá', 'departamento_id' => 2],
            ['nombre' => 'Apartadó', 'departamento_id' => 2],
            ['nombre' => 'Arboletes', 'departamento_id' => 2],
            ['nombre' => 'Argelia', 'departamento_id' => 2],
            ['nombre' => 'Armenia', 'departamento_id' => 2],
            ['nombre' => 'Barbosa', 'departamento_id' => 2],
            ['nombre' => 'Belmira', 'departamento_id' => 2],
            ['nombre' => 'Bello', 'departamento_id' => 2],
            ['nombre' => 'Betania', 'departamento_id' => 2],
            ['nombre' => 'Betulia', 'departamento_id' => 2],
            ['nombre' => 'Briceño', 'departamento_id' => 2],
            ['nombre' => 'Buriticá', 'departamento_id' => 2],
            ['nombre' => 'Cáceres', 'departamento_id' => 2],
            ['nombre' => 'Caicedo', 'departamento_id' => 2],
            ['nombre' => 'Caldas', 'departamento_id' => 2],
            ['nombre' => 'Campamento', 'departamento_id' => 2],
            ['nombre' => 'Cañasgordas', 'departamento_id' => 2],
            ['nombre' => 'Caracolí', 'departamento_id' => 2],
            ['nombre' => 'Caramanta', 'departamento_id' => 2],
            ['nombre' => 'Carepa', 'departamento_id' => 2],
            ['nombre' => 'Carolina del Príncipe', 'departamento_id' => 2],
            ['nombre' => 'Caucasia', 'departamento_id' => 2],
            ['nombre' => 'Chigorodó', 'departamento_id' => 2],
            ['nombre' => 'Cisneros', 'departamento_id' => 2],
            ['nombre' => 'Cocorná', 'departamento_id' => 2],
            ['nombre' => 'Concepción', 'departamento_id' => 2],
            ['nombre' => 'Concordia', 'departamento_id' => 2],
            ['nombre' => 'Copacabana', 'departamento_id' => 2],
            ['nombre' => 'Dabeiba', 'departamento_id' => 2],
            ['nombre' => 'Donmatías', 'departamento_id' => 2],
            ['nombre' => 'Ebéjico', 'departamento_id' => 2],
            ['nombre' => 'El Bagre', 'departamento_id' => 2],
            ['nombre' => 'El Carmen de Viboral', 'departamento_id' => 2],
            ['nombre' => 'El Peñol', 'departamento_id' => 2],
            ['nombre' => 'El Retiro', 'departamento_id' => 2],
            ['nombre' => 'El Santuario', 'departamento_id' => 2],
            ['nombre' => 'Entrerríos', 'departamento_id' => 2],
            ['nombre' => 'Envigado', 'departamento_id' => 2],
            ['nombre' => 'Fredonia', 'departamento_id' => 2],
            ['nombre' => 'Frontino', 'departamento_id' => 2],
            ['nombre' => 'Giraldo', 'departamento_id' => 2],
            ['nombre' => 'Girardota', 'departamento_id' => 2],
            ['nombre' => 'Gómez Plata', 'departamento_id' => 2],
            ['nombre' => 'Granada', 'departamento_id' => 2],
            ['nombre' => 'Guadalupe', 'departamento_id' => 2],
            ['nombre' => 'Guarne', 'departamento_id' => 2],
            ['nombre' => 'Guatapé', 'departamento_id' => 2],
            ['nombre' => 'Heliconia', 'departamento_id' => 2],
            ['nombre' => 'Hispania', 'departamento_id' => 2],
            ['nombre' => 'Itagüí', 'departamento_id' => 2],
            ['nombre' => 'Ituango', 'departamento_id' => 2],
            ['nombre' => 'Jardín', 'departamento_id' => 2],
            ['nombre' => 'Jericó', 'departamento_id' => 2],
            ['nombre' => 'La Ceja', 'departamento_id' => 2],
            ['nombre' => 'La Estrella', 'departamento_id' => 2],
            ['nombre' => 'La Pintada', 'departamento_id' => 2],
            ['nombre' => 'La Unión', 'departamento_id' => 2],
            ['nombre' => 'Liborina', 'departamento_id' => 2],
            ['nombre' => 'Maceo', 'departamento_id' => 2],
            ['nombre' => 'Marinilla', 'departamento_id' => 2],
            ['nombre' => 'Medellín', 'departamento_id' => 2],
            ['nombre' => 'Montebello', 'departamento_id' => 2],
            ['nombre' => 'Murindó', 'departamento_id' => 2],
            ['nombre' => 'Mutatá', 'departamento_id' => 2],
            ['nombre' => 'Nariño', 'departamento_id' => 2],
            ['nombre' => 'Nechí', 'departamento_id' => 2],
            ['nombre' => 'Necoclí', 'departamento_id' => 2],
            ['nombre' => 'Olaya', 'departamento_id' => 2],
            ['nombre' => 'Peque', 'departamento_id' => 2],
            ['nombre' => 'Pueblorrico', 'departamento_id' => 2],
            ['nombre' => 'Puerto Berrío', 'departamento_id' => 2],
            ['nombre' => 'Puerto Nare', 'departamento_id' => 2],
            ['nombre' => 'Puerto Triunfo', 'departamento_id' => 2],
            ['nombre' => 'Remedios', 'departamento_id' => 2],
            ['nombre' => 'Retiro', 'departamento_id' => 2],
            ['nombre' => 'Rionegro', 'departamento_id' => 2],
            ['nombre' => 'Sabanalarga', 'departamento_id' => 2],
            ['nombre' => 'Sabaneta', 'departamento_id' => 2],
            ['nombre' => 'Salgar', 'departamento_id' => 2],
            ['nombre' => 'San Andrés de Cuerquia', 'departamento_id' => 2],
            ['nombre' => 'San Carlos', 'departamento_id' => 2],
            ['nombre' => 'San Francisco', 'departamento_id' => 2],
            ['nombre' => 'San Jerónimo', 'departamento_id' => 2],
            ['nombre' => 'San José de la Montaña', 'departamento_id' => 2],
            ['nombre' => 'San Juan de Urabá', 'departamento_id' => 2],
            ['nombre' => 'San Luis', 'departamento_id' => 2],
            ['nombre' => 'San Pedro de los Milagros', 'departamento_id' => 2],
            ['nombre' => 'San Pedro de Urabá', 'departamento_id' => 2],
            ['nombre' => 'San Rafael', 'departamento_id' => 2],
            ['nombre' => 'San Roque', 'departamento_id' => 2],
            ['nombre' => 'San Vicente', 'departamento_id' => 2],
            ['nombre' => 'Santa Bárbara', 'departamento_id' => 2],
            ['nombre' => 'Santa Rosa de Osos', 'departamento_id' => 2],
            ['nombre' => 'Santo Domingo', 'departamento_id' => 2],
            ['nombre' => 'Segovia', 'departamento_id' => 2],
            ['nombre' => 'Sonsón', 'departamento_id' => 2],
            ['nombre' => 'Sopetrán', 'departamento_id' => 2],
            ['nombre' => 'Támesis', 'departamento_id' => 2],
            ['nombre' => 'Tarazá', 'departamento_id' => 2],
            ['nombre' => 'Tarso', 'departamento_id' => 2],
            ['nombre' => 'Titiribí', 'departamento_id' => 2],
            ['nombre' => 'Toledo', 'departamento_id' => 2],
            ['nombre' => 'Turbo', 'departamento_id' => 2],
            ['nombre' => 'Uramita', 'departamento_id' => 2],
            ['nombre' => 'Urrao', 'departamento_id' => 2],
            ['nombre' => 'Valdivia', 'departamento_id' => 2],
            ['nombre' => 'Valparaíso', 'departamento_id' => 2],
            ['nombre' => 'Vegachí', 'departamento_id' => 2],
            ['nombre' => 'Venecia', 'departamento_id' => 2],
            ['nombre' => 'Vigía del Fuerte', 'departamento_id' => 2],
            ['nombre' => 'Yalí', 'departamento_id' => 2],
            ['nombre' => 'Yarumal', 'departamento_id' => 2],
            ['nombre' => 'Yolombó', 'departamento_id' => 2],
            ['nombre' => 'Yondó', 'departamento_id' => 2],
            ['nombre' => 'Zaragoza', 'departamento_id' => 2],
            ['nombre' => 'Leticia', 'departamento_id' => 1],
            ['nombre' => 'Puerto Nariño', 'departamento_id' => 1],
            ['nombre' => 'La Chorrera', 'departamento_id' => 1],
            ['nombre' => 'La Pedrera', 'departamento_id' => 1],
            ['nombre' => 'La Victoria', 'departamento_id' => 1],
            ['nombre' => 'Miriti - Paraná', 'departamento_id' => 1],
            ['nombre' => 'Puerto Alegría', 'departamento_id' => 1],
            ['nombre' => 'Puerto Arica', 'departamento_id' => 1],
            ['nombre' => 'Puerto Santander', 'departamento_id' => 1],
            ['nombre' => 'Tarapacá', 'departamento_id' => 1],
            ['nombre' => 'El Encanto', 'departamento_id' => 1],
            ['nombre' => 'Arauca', 'departamento_id' => 3],
            ['nombre' => 'Arauquita', 'departamento_id' => 3],
            ['nombre' => 'Cravo Norte', 'departamento_id' => 3],
            ['nombre' => 'Fortul', 'departamento_id' => 3],
            ['nombre' => 'Puerto Rondón', 'departamento_id' => 3],
            ['nombre' => 'Saravena', 'departamento_id' => 3],
            ['nombre' => 'Tame', 'departamento_id' => 3],
            ['nombre' => 'Barranquilla', 'departamento_id' => 4],
            ['nombre' => 'Baranoa', 'departamento_id' => 4],
            ['nombre' => 'Campo de la Cruz', 'departamento_id' => 4],
            ['nombre' => 'Candelaria', 'departamento_id' => 4],
            ['nombre' => 'Galapa', 'departamento_id' => 4],
            ['nombre' => 'Juan de Acosta', 'departamento_id' => 4],
            ['nombre' => 'Luruaco', 'departamento_id' => 4],
            ['nombre' => 'Malambo', 'departamento_id' => 4],
            ['nombre' => 'Manatí', 'departamento_id' => 4],
            ['nombre' => 'Palmar de Varela', 'departamento_id' => 4],
            ['nombre' => 'Piojó', 'departamento_id' => 4],
            ['nombre' => 'Polonuevo', 'departamento_id' => 4],
            ['nombre' => 'Ponedera', 'departamento_id' => 4],
            ['nombre' => 'Puerto Colombia', 'departamento_id' => 4],
            ['nombre' => 'Repelón', 'departamento_id' => 4],
            ['nombre' => 'Sabanagrande', 'departamento_id' => 4],
            ['nombre' => 'Sabanalarga', 'departamento_id' => 4],
            ['nombre' => 'Santa Lucía', 'departamento_id' => 4],
            ['nombre' => 'Santo Tomás', 'departamento_id' => 4],
            ['nombre' => 'Soledad', 'departamento_id' => 4],
            ['nombre' => 'Suan', 'departamento_id' => 4],
            ['nombre' => 'Tubará', 'departamento_id' => 4],
            ['nombre' => 'Usiacurí', 'departamento_id' => 4],
            ['nombre' => 'Achí', 'departamento_id' => 5],
            ['nombre' => 'Altos del Rosario', 'departamento_id' => 5],
            ['nombre' => 'Arenal', 'departamento_id' => 5],
            ['nombre' => 'Arjona', 'departamento_id' => 5],
            ['nombre' => 'Arroyohondo', 'departamento_id' => 5],
            ['nombre' => 'Barranco de Loba', 'departamento_id' => 5],
            ['nombre' => 'Calamar', 'departamento_id' => 5],
            ['nombre' => 'Cantagallo', 'departamento_id' => 5],
            ['nombre' => 'Cartagena', 'departamento_id' => 5],
            ['nombre' => 'Cicuco', 'departamento_id' => 5],
            ['nombre' => 'Clemencia', 'departamento_id' => 5],
            ['nombre' => 'Córdoba', 'departamento_id' => 5],
            ['nombre' => 'El Carmen de Bolívar', 'departamento_id' => 5],
            ['nombre' => 'El Guamo', 'departamento_id' => 5],
            ['nombre' => 'El Peñón', 'departamento_id' => 5],
            ['nombre' => 'Hatillo de Loba', 'departamento_id' => 5],
            ['nombre' => 'Magangué', 'departamento_id' => 5],
            ['nombre' => 'Mahates', 'departamento_id' => 5],
            ['nombre' => 'Margarita', 'departamento_id' => 5],
            ['nombre' => 'María la Baja', 'departamento_id' => 5],
            ['nombre' => 'Montecristo', 'departamento_id' => 5],
            ['nombre' => 'Morales', 'departamento_id' => 5],
            ['nombre' => 'Norosí', 'departamento_id' => 5],
            ['nombre' => 'Pinillos', 'departamento_id' => 5],
            ['nombre' => 'Regidor', 'departamento_id' => 5],
            ['nombre' => 'Río Viejo', 'departamento_id' => 5],
            ['nombre' => 'San Cristóbal', 'departamento_id' => 5],
            ['nombre' => 'San Estanislao', 'departamento_id' => 5],
            ['nombre' => 'San Fernando', 'departamento_id' => 5],
            ['nombre' => 'San Jacinto', 'departamento_id' => 5],
            ['nombre' => 'San Jacinto del Cauca', 'departamento_id' => 5],
            ['nombre' => 'San Juan Nepomuceno', 'departamento_id' => 5],
            ['nombre' => 'San Martín de Loba', 'departamento_id' => 5],
            ['nombre' => 'San Pablo', 'departamento_id' => 5],
            ['nombre' => 'Santa Catalina', 'departamento_id' => 5],
            ['nombre' => 'Santa Rosa', 'departamento_id' => 5],
            ['nombre' => 'Santa Rosa del Sur', 'departamento_id' => 5],
            ['nombre' => 'Sibundoy', 'departamento_id' => 5],
            ['nombre' => 'Simití', 'departamento_id' => 5],
            ['nombre' => 'Soplaviento', 'departamento_id' => 5],
            ['nombre' => 'Talaigua Nuevo', 'departamento_id' => 5],
            ['nombre' => 'Tiquisio', 'departamento_id' => 5],
            ['nombre' => 'Turbaco', 'departamento_id' => 5],
            ['nombre' => 'Turbaná', 'departamento_id' => 5],
            ['nombre' => 'Villanueva', 'departamento_id' => 5],
            ['nombre' => 'Zambrano', 'departamento_id' => 5],
            ['nombre' => 'Almeida', 'departamento_id' => 6],
            ['nombre' => 'Aquitania', 'departamento_id' => 6],
            ['nombre' => 'Arcabuco', 'departamento_id' => 6],
            ['nombre' => 'Belén', 'departamento_id' => 6],
            ['nombre' => 'Berbeo', 'departamento_id' => 6],
            ['nombre' => 'Betéitiva', 'departamento_id' => 6],
            ['nombre' => 'Boavita', 'departamento_id' => 6],
            ['nombre' => 'Boyacá', 'departamento_id' => 6],
            ['nombre' => 'Briceño', 'departamento_id' => 6],
            ['nombre' => 'Buenavista', 'departamento_id' => 6],
            ['nombre' => 'Busbanzá', 'departamento_id' => 6],
            ['nombre' => 'Caldas', 'departamento_id' => 6],
            ['nombre' => 'Campohermoso', 'departamento_id' => 6],
            ['nombre' => 'Cerinza', 'departamento_id' => 6],
            ['nombre' => 'Chinavita', 'departamento_id' => 6],
            ['nombre' => 'Chiquinquirá', 'departamento_id' => 6],
            ['nombre' => 'Chiscas', 'departamento_id' => 6],
            ['nombre' => 'Chita', 'departamento_id' => 6],
            ['nombre' => 'Chitaraque', 'departamento_id' => 6],
            ['nombre' => 'Chivatá', 'departamento_id' => 6],
            ['nombre' => 'Chíquiza', 'departamento_id' => 6],
            ['nombre' => 'Cómbita', 'departamento_id' => 6],
            ['nombre' => 'Coper', 'departamento_id' => 6],
            ['nombre' => 'Corrales', 'departamento_id' => 6],
            ['nombre' => 'Covarachía', 'departamento_id' => 6],
            ['nombre' => 'Cubará', 'departamento_id' => 6],
            ['nombre' => 'Cucaita', 'departamento_id' => 6],
            ['nombre' => 'Cuítiva', 'departamento_id' => 6],
            ['nombre' => 'Duitama', 'departamento_id' => 6],
            ['nombre' => 'El Cocuy', 'departamento_id' => 6],
            ['nombre' => 'El Espino', 'departamento_id' => 6],
            ['nombre' => 'Firavitoba', 'departamento_id' => 6],
            ['nombre' => 'Floresta', 'departamento_id' => 6],
            ['nombre' => 'Gachantivá', 'departamento_id' => 6],
            ['nombre' => 'Gámeza', 'departamento_id' => 6],
            ['nombre' => 'Garagoa', 'departamento_id' => 6],
            ['nombre' => 'Guacamayas', 'departamento_id' => 6],
            ['nombre' => 'Guateque', 'departamento_id' => 6],
            ['nombre' => 'Guayatá', 'departamento_id' => 6],
            ['nombre' => 'Güicán', 'departamento_id' => 6],
            ['nombre' => 'Iza', 'departamento_id' => 6],
            ['nombre' => 'Jenesano', 'departamento_id' => 6],
            ['nombre' => 'Jericó', 'departamento_id' => 6],
            ['nombre' => 'La Capilla', 'departamento_id' => 6],
            ['nombre' => 'La Uvita', 'departamento_id' => 6],
            ['nombre' => 'La Victoria', 'departamento_id' => 6],
            ['nombre' => 'Labranzagrande', 'departamento_id' => 6],
            ['nombre' => 'Macanal', 'departamento_id' => 6],
            ['nombre' => 'Maripí', 'departamento_id' => 6],
            ['nombre' => 'Miraflores', 'departamento_id' => 6],
            ['nombre' => 'Mongua', 'departamento_id' => 6],
            ['nombre' => 'Monguí', 'departamento_id' => 6],
            ['nombre' => 'Moniquirá', 'departamento_id' => 6],
            ['nombre' => 'Motavita', 'departamento_id' => 6],
            ['nombre' => 'Muzo', 'departamento_id' => 6],
            ['nombre' => 'Nobsa', 'departamento_id' => 6],
            ['nombre' => 'Nuevo Colón', 'departamento_id' => 6],
            ['nombre' => 'Oicatá', 'departamento_id' => 6],
            ['nombre' => 'Otanche', 'departamento_id' => 6],
            ['nombre' => 'Pachavita', 'departamento_id' => 6],
            ['nombre' => 'Páez', 'departamento_id' => 6],
            ['nombre' => 'Paipa', 'departamento_id' => 6],
            ['nombre' => 'Pajarito', 'departamento_id' => 6],
            ['nombre' => 'Panqueba', 'departamento_id' => 6],
            ['nombre' => 'Pauna', 'departamento_id' => 6],
            ['nombre' => 'Paya', 'departamento_id' => 6],
            ['nombre' => 'Paz de Río', 'departamento_id' => 6],
            ['nombre' => 'Pesca', 'departamento_id' => 6],
            ['nombre' => 'Pisba', 'departamento_id' => 6],
            ['nombre' => 'Puerto Boyacá', 'departamento_id' => 6],
            ['nombre' => 'Quípama', 'departamento_id' => 6],
            ['nombre' => 'Ramiriquí', 'departamento_id' => 6],
            ['nombre' => 'Ráquira', 'departamento_id' => 6],
            ['nombre' => 'Rondón', 'departamento_id' => 6],
            ['nombre' => 'Saboyá', 'departamento_id' => 6],
            ['nombre' => 'Sáchica', 'departamento_id' => 6],
            ['nombre' => 'Samacá', 'departamento_id' => 6],
            ['nombre' => 'San Eduardo', 'departamento_id' => 6],
            ['nombre' => 'San José de Pare', 'departamento_id' => 6],
            ['nombre' => 'San Luis de Gaceno', 'departamento_id' => 6],
            ['nombre' => 'San Mateo', 'departamento_id' => 6],
            ['nombre' => 'San Miguel de Sema', 'departamento_id' => 6],
            ['nombre' => 'San Pablo de Borbur', 'departamento_id' => 6],
            ['nombre' => 'Santa María', 'departamento_id' => 6],
            ['nombre' => 'Santa Rosa de Viterbo', 'departamento_id' => 6],
            ['nombre' => 'Santa Sofía', 'departamento_id' => 6],
            ['nombre' => 'Santana', 'departamento_id' => 6],
            ['nombre' => 'Sativanorte', 'departamento_id' => 6],
            ['nombre' => 'Sativasur', 'departamento_id' => 6],
            ['nombre' => 'Siachoque', 'departamento_id' => 6],
            ['nombre' => 'Soatá', 'departamento_id' => 6],
            ['nombre' => 'Socha', 'departamento_id' => 6],
            ['nombre' => 'Socotá', 'departamento_id' => 6],
            ['nombre' => 'Sogamoso', 'departamento_id' => 6],
            ['nombre' => 'Somondoco', 'departamento_id' => 6],
            ['nombre' => 'Sora', 'departamento_id' => 6],
            ['nombre' => 'Soracá', 'departamento_id' => 6],
            ['nombre' => 'Sotaquirá', 'departamento_id' => 6],
            ['nombre' => 'Susacón', 'departamento_id' => 6],
            ['nombre' => 'Sutamarchán', 'departamento_id' => 6],
            ['nombre' => 'Sutatenza', 'departamento_id' => 6],
            ['nombre' => 'Tenza', 'departamento_id' => 6],
            ['nombre' => 'Tibaná', 'departamento_id' => 6],
            ['nombre' => 'Tibasosa', 'departamento_id' => 6],
            ['nombre' => 'Tinjacá', 'departamento_id' => 6],
            ['nombre' => 'Tipacoque', 'departamento_id' => 6],
            ['nombre' => 'Toca', 'departamento_id' => 6],
            ['nombre' => 'Togüí', 'departamento_id' => 6],
            ['nombre' => 'Tópaga', 'departamento_id' => 6],
            ['nombre' => 'Tota', 'departamento_id' => 6],
            ['nombre' => 'Tunja', 'departamento_id' => 6],
            ['nombre' => 'Turmequé', 'departamento_id' => 6],
            ['nombre' => 'Tuta', 'departamento_id' => 6],
            ['nombre' => 'Tutazá', 'departamento_id' => 6],
            ['nombre' => 'Úmbita', 'departamento_id' => 6],
            ['nombre' => 'Ventaquemada', 'departamento_id' => 6],
            ['nombre' => 'Villa de Leyva', 'departamento_id' => 6],
            ['nombre' => 'Viracachá', 'departamento_id' => 6],
            ['nombre' => 'Zetaquira', 'departamento_id' => 6],
            ['nombre' => 'Aguadas', 'departamento_id' => 7],
            ['nombre' => 'Anserma', 'departamento_id' => 7],
            ['nombre' => 'Aranzazu', 'departamento_id' => 7],
            ['nombre' => 'Belalcázar', 'departamento_id' => 7],
            ['nombre' => 'Chinchiná', 'departamento_id' => 7],
            ['nombre' => 'Filadelfia', 'departamento_id' => 7],
            ['nombre' => 'La Dorada', 'departamento_id' => 7],
            ['nombre' => 'La Merced', 'departamento_id' => 7],
            ['nombre' => 'Manizales', 'departamento_id' => 7],
            ['nombre' => 'Manzanares', 'departamento_id' => 7],
            ['nombre' => 'Marmato', 'departamento_id' => 7],
            ['nombre' => 'Marquetalia', 'departamento_id' => 7],
            ['nombre' => 'Marulanda', 'departamento_id' => 7],
            ['nombre' => 'Neira', 'departamento_id' => 7],
            ['nombre' => 'Norcasia', 'departamento_id' => 7],
            ['nombre' => 'Pácora', 'departamento_id' => 7],
            ['nombre' => 'Palestina', 'departamento_id' => 7],
            ['nombre' => 'Pensilvania', 'departamento_id' => 7],
            ['nombre' => 'Riosucio', 'departamento_id' => 7],
            ['nombre' => 'Risaralda', 'departamento_id' => 7],
            ['nombre' => 'Salamina', 'departamento_id' => 7],
            ['nombre' => 'Samaná', 'departamento_id' => 7],
            ['nombre' => 'San José', 'departamento_id' => 7],
            ['nombre' => 'Supía', 'departamento_id' => 7],
            ['nombre' => 'Victoria', 'departamento_id' => 7],
            ['nombre' => 'Villamaría', 'departamento_id' => 7],
            ['nombre' => 'Viterbo', 'departamento_id' => 7],
        ];

        foreach ($ciudades as $ciudad) {
            DB::table('ciudades')->insert($ciudad);
        }
    }
}
